package main

import (
	"fmt"
	"log"

	"backend-template/internal/config"
	"backend-template/internal/database"
	"backend-template/routes"

	// Swagger docs imports (auto-generated by swag init)
	_ "backend-template/docs"                       // Global swagger (all modules)
	_ "backend-template/internal/modules/auth/docs" // Auth module swagger

	"github.com/gofiber/contrib/v3/swaggo"
	"github.com/gofiber/fiber/v3"
	"github.com/gofiber/fiber/v3/middleware/cors"
	"github.com/gofiber/fiber/v3/middleware/logger"
	"github.com/gofiber/fiber/v3/middleware/recover"
)

// @title           Backend Template API
// @version         1.0.0
// @description     A production-ready RESTful backend with JWT authentication (Access + Refresh tokens), Role-Based Access Control, and Clean Architecture.
// @host            localhost:8080
// @BasePath        /
// @securityDefinitions.apikey  BearerAuth
// @in                          header
// @name                        Authorization
func main() {
	// Load environment configuration
	config.LoadConfig()

	// Connect to database
	database.ConnectDB()

	// AutoMigrate models
	database.AutoMigrate()

	// Create Fiber app with custom error handler
	app := fiber.New(fiber.Config{
		AppName: "Backend Template v1.1.0",
		ErrorHandler: func(c fiber.Ctx, err error) error {
			code := fiber.StatusInternalServerError
			if e, ok := err.(*fiber.Error); ok {
				code = e.Code
			}
			return c.Status(code).JSON(fiber.Map{
				"success": false,
				"message": err.Error(),
			})
		},
	})

	// Global middleware
	app.Use(logger.New())
	app.Use(recover.New())
	app.Use(cors.New(cors.Config{
		AllowOrigins: []string{"*"},
		AllowHeaders: []string{"Origin", "Content-Type", "Accept", "Authorization"},
		AllowMethods: []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
	}))

	// Swagger documentation endpoints
	// Auth-specific swagger (must be registered BEFORE global to avoid wildcard conflict)
	app.Get("/swagger/auth/*", swaggo.New(swaggo.Config{
		InstanceName: "auth",
		Title:        "Auth Service API",
	}))

	// Global swagger (all modules)
	app.Get("/swagger/*", swaggo.HandlerDefault)

	// Setup API routes
	routes.SetupRoutes(app)

	// Start server
	port := config.AppConfig.AppPort
	log.Printf("Server starting on port %s", port)
	log.Printf("Swagger (All):  http://localhost:%s/swagger/index.html", port)
	log.Printf("Swagger (Auth): http://localhost:%s/swagger/auth/index.html", port)
	log.Fatal(app.Listen(fmt.Sprintf(":%s", port)))
}
